# Generated by Django 5.2.4 on 2025-07-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
