# Generated by Django 5.2.4 on 2025-07-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('FamilyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mediapp.family'),
        ),
    ]
